# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
                - name: Web Request
  # You may pin to the exact commit or the version.
  # uses: cssnr/web-request-action@8818b92ef62275af0d75ef6c61326deba96291c0
  uses: cssnr/web-request-action@v1.0.2
  with:
    # URL for Request
    url: 
    # Request Method
    method: # optional, default is POST
    # Request Data JSON
    data: # optional, default is {}
    # Request Headers JSON
    headers: # optional, default is {}
    # Request Parameters JSON
    params: # optional, default is {}
    # Basic Auth Username
    username: # optional
    # Basic Auth Password
    password: # optional
    # Ignore SSL Errors
    insecure: # optional, default is false
    # File Path
    file: # optional
    # File Key Name
    name: # optional, default is file
          
